<?php

namespace Database\Seeders;

use App\Models\Opd;
use Illuminate\Database\Seeder;

class OpdSeeder extends Seeder
{
    public function run(): void
    {
        $opds = [
            ['nama' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia', 'jenis' => 'Badan'],
            ['nama' => 'Badan Kesatuan Bangsa dan Politik', 'jenis' => 'Badan'],
            ['nama' => 'Badan Penanggulangan Bencana Daerah', 'jenis' => 'Badan'],
            ['nama' => 'Badan Pengelolaan Keuangan, Pendapatan dan Aset Daerah', 'jenis' => 'Badan'],
            ['nama' => 'Badan Perencanaan Pembangunan, Riset, dan Inovasi Daerah', 'jenis' => 'Badan'],
            ['nama' => 'Bagian Administrasi Pembangunan', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Hukum', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Kesejahteraan Rakyat', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Organisasi', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Pemerintahan', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Pengadaan Barang/Jasa', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Perekonomian dan Sumber Daya alam', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Protokol dan Komunikasi Pimpinan', 'jenis' => 'Bagian'],
            ['nama' => 'Bagian Umum', 'jenis' => 'Bagian'],
            ['nama' => 'Dinas Kebudayaan Kepemudaan dan Olahraga dan Pariwisata', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Kependudukan dan Pencatatan Sipil', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Kesehatan', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Ketahanan Pangan dan Pertanian', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Komunikasi dan Informatika', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Koperasi Usaha Kecil Menengah dan Perdagangan', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Lingkungan Hidup', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Pekerjaan Umum dan Penataan Ruang', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Pemberdayaan Masyarakat dan Desa', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Pendidikan', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Perhubungan', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Perindustrian dan Tenaga Kerja', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Perpustakaan dan Kearsipan', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Perumahan Rakyat dan Kawasan Permukiman', 'jenis' => 'Dinas'],
            ['nama' => 'Dinas Sosial P3AKB', 'jenis' => 'Dinas'],
            ['nama' => 'Inspektorat', 'jenis' => 'Inspektorat'],
            ['nama' => 'Kecamatan Bayat', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Cawas', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Ceper', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Delanggu', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Gantiwarno', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Jatinom', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Jogonalan', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Juwiring', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Kalikotes', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Karanganom', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Karangdowo', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Karangnongko', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Kemalang', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Klaten Selatan', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Klaten Selatan dan Kabupaten Klaten', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Klaten Tengah', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Klaten Utara', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Manisrenggo', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Ngawen', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Pedan', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Polanharjo', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Prambanan', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Trucuk', 'jenis' => 'Kecamatan'],
            ['nama' => 'kecamatan Tulung', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kecamatan Wedi', 'jenis' => 'Kecamatan'],
            ['nama' => 'Kelurahan Bareng', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Bareng Lor', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Buntalan', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Gayamprit', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Gergunung', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Jatinom', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Kabupaten', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Klaten', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Mojayan', 'jenis' => 'Kelurahan'],
            ['nama' => 'Kelurahan Tonggalan', 'jenis' => 'Kelurahan'],
            ['nama' => 'Puskesmas Bayat', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Cawas I', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Cawas II', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Ceper', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Delanggu', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Gantiwarno', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Jambukulon', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Jatinom', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Jogonalan I', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Jogonalan II', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Juwiring', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Kalikotes', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Karanganom', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Karangdowo', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Karangnongko', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Kayumas', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Kebonarum', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Kebondalem Lor', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Kemalang', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Klaten Selatan', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Klaten Tengah', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Klaten Utara', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Majegan', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Manisrenggo', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Ngawen', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Pedan', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Polanharjo', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Prambanan', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Trucuk I', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Trucuk II', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Tulung', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Wedi', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Wonosari I', 'jenis' => 'Puskesmas'],
            ['nama' => 'Puskesmas Wonosari II', 'jenis' => 'Puskesmas'],
            ['nama' => 'RSUD Bagas Waras', 'jenis' => 'RSUD'],
            ['nama' => 'Satuan Polisi Pamong Praja dan Pemadam Kebakaran', 'jenis' => 'Satuan'],
            ['nama' => 'Sekretariat DPRD', 'jenis' => 'Sekretariat'],
        ];

        foreach ($opds as $opd) {
            Opd::firstOrCreate(
                ['nama' => $opd['nama']],
                ['jenis' => $opd['jenis'], 'is_active' => true]
            );
        }
    }
};
